### PR TITLE
Fix build process by rolling back schema-inspector dependency to 1.6.8.

### PR DESCRIPTION
**Pull request by mattwelke**

### CODE REVIEW

**Review by ColinCampbell-GBI — COMMENTED** [review]
This works as a temp fix, but don't we need to ensure the webpack config is transpiling code down correctly? Otherwise, this can continue happening every time we update dependencies

**Review by ColinCampbell-GBI — APPROVED** [review]
This works as a temp fix, but don't we need to ensure the webpack config is transpiling code down correctly? Otherwise, this can continue happening every time we update dependencies

**Comment by mattwelke** [comment]
Yes, the ticket includes a plan for a long term investigation. To prevent this from happening in future dependency updates, I've pinned the version of schema-inspector to 1.6.8 instead of allowing ^1.6.8.

**Comment by mattwelke** [comment]
Yes, the ticket includes a plan for a long term investigation. To prevent this from happening in future dependency updates, I've pinned the version of schema-inspector to 1.6.8 instead of allowing ^1.6.8.

**Pull request merged**
